### ISSUE TITLE
Security Advisories

### ISSUE THREAD

**Issue by DlieBG** [Berufskolleg-Bocholt-West/TicketManagementJJJ#1]
Nehmt die hardcoded Zugangsdaten aus dem Code und aus dem Repo!
Wie wäre es mit modernen Umgebungsvariablen?
@Johannes-01 @JuFrBK

**Comment by Johannes-01** [comment]
Hallo Herr Schwering,

Danke für deine konstruktive Kritik. ;)
Ich schätze es sehr das du dir die Zeit genommen hast, um unseren Code zu
“reviewen”. Ich erwarte die Rechnung in kürze.  Ich werde natürlich sofort
die Hardcode Zugangsdaten aus dem Repo entfernen, sodass niemand auf diese
vertraulichen Daten mehr zugreifen kann. Allerdings die Variablen Benennung
jetzt noch zu ändern wäre mir schlicht und ergreifend zu viel Arbeit.

Mit freundlichen Grüßen,

Johannes Haick.

**Comment by Johannes-01** [comment]
All done :)
